from django.contrib import admin
from .models import *

admin.site.register(Admins)
admin.site.register(Ads)
admin.site.register(AboutUs)
admin.site.register(Client)
admin.site.register(ClientIPLogList)
admin.site.register(AdminCodeGen)
admin.site.register(ClientCodeGen)
admin.site.register(Branch)
admin.site.register(SuperCategory)
admin.site.register(Category)
admin.site.register(SubCategory)
admin.site.register(Brand)
admin.site.register(Gender)
admin.site.register(Color)
admin.site.register(Size)
admin.site.register(Update)
admin.site.register(Visited)
admin.site.register(Location)
admin.site.register(Message)
admin.site.register(Exchange)
admin.site.register(Discount)
admin.site.register(Product)
admin.site.register(Order)